# Generated by Django 3.1.4 on 2020-12-21 14:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('receiver', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('is_friend', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Friends',
            },
        ),
    ]
