# Generated by Django 3.1.4 on 2020-12-21 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201221_2013'),
        ('friends', '0002_auto_20201221_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friends',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Receiver', to='users.profile'),
        ),
        migrations.AlterField(
            model_name='friends',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Sender', to='users.profile'),
        ),
    ]
