# Generated by Django 3.1.4 on 2020-12-21 08:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('bio', models.CharField(default='', max_length=500, null=True)),
                ('friends', models.ManyToManyField(blank=True, to='users.Users')),
            ],
        ),
    ]
