# Generated by Django 3.1.4 on 2020-12-21 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='profile_pic',
            field=models.ImageField(blank=True, default='', upload_to='media/'),
        ),
    ]
