# Generated by Django 3.1.4 on 2020-12-30 08:59

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('desc', models.CharField(max_length=256, null=True)),
                ('type', models.CharField(choices=[('TXT', 'Text'), ('VDO', 'Video'), ('ADO', 'Audio'), ('IMG', 'Image')], default='TXT', max_length=20)),
                ('title', models.CharField(max_length=256, null=True)),
                ('media', models.CharField(max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=256, null=True)),
                ('user_email', models.EmailField(max_length=256)),
                ('password', models.CharField(max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShoutReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('shout_id', models.ForeignKey(default='', editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ReportedPost', to='comment_like_report.shout')),
                ('user_id', models.ForeignKey(default='', editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Report_User', to='comment_like_report.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ShoutLike',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('shout_id', models.ForeignKey(default='', editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='LikedPost', to='comment_like_report.shout')),
                ('user_id', models.ForeignKey(default='', editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Like_User', to='comment_like_report.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ShoutComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment', models.CharField(max_length=256, null=True)),
                ('date', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('shout_id', models.ForeignKey(default='', editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserPost', to='comment_like_report.shout')),
                ('user_id', models.ForeignKey(default='', editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Comment_User', to='comment_like_report.userprofile')),
            ],
        ),
        migrations.AddField(
            model_name='shout',
            name='user_id',
            field=models.ForeignKey(default='', editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Shout_User', to='comment_like_report.userprofile'),
        ),
    ]
