# Generated by Django 3.1.4 on 2020-12-21 12:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shout',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('desc', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=225)),
                ('dateStamp', models.DateTimeField(blank=True)),
                ('media', models.CharField(max_length=225)),
                ('c_id', models.CharField(max_length=3)),
                ('l_id', models.CharField(max_length=3)),
                ('r_id', models.CharField(max_length=3)),
                ('u_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ShoutComment',
            fields=[
                ('c_id', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('dateStamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='comment_like_report.shoutcomment')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comment_like_report.shout')),
                ('u_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
