# Generated by Django 3.1.4 on 2020-12-21 08:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('post_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('post_type', models.CharField(choices=[('T', 'Text'), ('I', 'Image'), ('V', 'Video'), ('A', 'Audio')], default='T', max_length=2)),
                ('title', models.CharField(default='', max_length=500, null=True)),
                ('description', models.CharField(default='', max_length=1000, null=True)),
                ('media', models.FileField(upload_to='media/')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.users')),
            ],
        ),
    ]
