# Generated by Django 3.1.4 on 2020-12-21 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='media',
            field=models.FileField(default='', null=True, upload_to='media/'),
        ),
    ]
