# Generated by Django 3.1.4 on 2020-12-21 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20201221_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='media',
            field=models.FileField(blank=True, default='', null=True, upload_to='media/'),
        ),
    ]
