# Generated by Django 3.1.4 on 2020-12-23 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201221_1413'),
        ('posts', '0011_auto_20201223_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to='users.users'),
        ),
    ]
