# Generated by Django 3.1.4 on 2020-12-24 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_auto_20201224_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='date_posted',
            field=models.DateField(blank=True, null=True),
        ),
    ]
