# Generated by Django 3.1.4 on 2020-12-24 11:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0023_auto_20201224_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='date_posted',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
