# Generated by Django 3.1.4 on 2020-12-28 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0025_auto_20201224_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='description',
            field=models.CharField(default='', max_length=1000, null=True),
        ),
    ]
